POST http://localhost:5000/v1/auth/register
Content-Type: application/json

{
    "userName":"Nguyen Tuan Anh",
    "email":"nguyentuananhfedev@gmail.com",
    "password":"T.a07082003"
}
###
POST http://localhost:5000/v1/auth/login
Content-Type: application/json

{
    "email":"nguyentuansanhfedev@gmail.com",
    "password":"T.a07082003"
}